FROM node as builder

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:18-buster-slim

# TODO mysql client

ENV PG_HOST=""
ENV PG_PORT=""
ENV PG_USER=""
ENV PG_PASS=""
ENV BACKUP_PATH=""
ENV TARGET_DB="[default]"

ENV MODE=""

ENV IBM_API_KEY_ID=""
ENV IBM_IAM_SERVICE_ID=""
ENV IBM_AUTH_ENDPOINT=""
ENV IBM_ENDPOINT=""

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm ci --production

COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 8080
CMD [ "node", "dist/index.js" ]